name: Build wheels

on:
  [workflow_dispatch]
  # push:
  # branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  # schedule:
  #   - cron: '0 0 * * 0,3' # 2/weekly

jobs:
  buildlinux:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.8", "3.9", "3.7"]
        platform: [x64]
        MB_ML_VER: ["2010", "2014", "_2_28"]
        PLAT: [x86_64]

    env:
      REPO_DIR: pinpoint-c-agent
      PKG_NAME: pinpointPy
      BUILD_COMMIT: master
      UNICODE_WIDTH: 32
      MB_PYTHON_VERSION: ${{ matrix.python-version }}
      TRAVIS_PYTHON_VERSION: ${{ matrix.python-version }}
      MB_ML_VER: ${{ matrix.MB_ML_VER }}
      PLAT: ${{ matrix.PLAT }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install VirtualEnv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: Build and Install Wheels
        run: |
          set -x
          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          echo "------- BEFORE INSTALL --------"
          # before_install
          # echo "------- CLEAN CODE --------"
          # clean_code $REPO_DIR $BUILD_COMMIT
          # echo "------- BUILD WHEEL --------"
          build_wheel $REPO_DIR $PLAT
          # echo "------- INSTALL_RUN --------"
          # install_run $PLAT
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/

  upload-pipy:
    runs-on: ubuntu-20.04
    needs: [buildlinux]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse/
      - name: Publish package to pypitest
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pinpoint }}
          packages_dir: wheelhouse/
